[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
